### ISSUE TITLE
Detect language

### ISSUE THREAD

**Issue by jarib** [liquidinvestigations/hoover-snoop2#104]
In the old snoop this was done by making [an extra request to Tika](https://github.com/hoover/snoop/blob/1f4fd7765e4f507ebf81ad406c2d472713924c13/snoop/digest.py#L97-L99), if the feature was enabled.

We should explore how much this affects indexing time.

Should be indexed to the `lang` field and then exposed as a facet filter in https://github.com/hoover/ui.

**Comment by germakoci** [comment]
would be great to keep this feature optional, so that it can be disabled/enabled depending on the type of data indexed as well as on the resources available for indexing

**Comment by germakoci** [comment]
reopening for suggestions from @grenwi

**Comment by grenwi** [comment]
Another well working solution: the language detection classifier from openNLP:
https://opennlp.apache.org/news/model-langdetect-183.html

The provided model is trained for 103 languages on well maintained standard corpora. The classifier itself is easy to use, fast (I usually call it on the first max 2500 chars of a document only) and very accurate.

An example how to call the Java based library from python via pexpect can be found here: https://github.com/curzona/opennlp-python

Maybe also interesting: Integration with Python's nltk can be found here: https://github.com/paudan/opennlp_python
