### ISSUE TITLE
Collapsing multiple blank lines

### ISSUE THREAD

**Issue by grenwi** [liquidinvestigations/hoover-snoop2#131]
For some Excel (and other?) files, Tika extracts hundreds of thousands of blank lines (representing empty cells). This breaks fulltext view of the search UI and information extraction (as performed in newsleak).

I suggest collapsing of multiple blank lines to a maximum number (e.g. 50).

**Comment by gabriel-v** [comment]
I remember something about limiting this, but it may not have made it into the tree.

Let's replicate the problem with a large empty Excel spreadsheet to be added to https://github.com/hoover/testdata, decide on a number continuous newlines to be capped (at 4? 6?) probably over [here where we combine all the texts](https://github.com/hoover/snoop2/blob/dbdd60aced79ec50f0ecce93a4619d50d5b54211/snoop/data/digests.py#L74).

**Comment by mgax** [comment]
> I remember something about limiting this, but it may not have made it into the tree.

Nah, it was about whitespace at the start and end, and we just slapped a `.trim()` on it.

**Comment by mgax** [comment]
https://github.com/hoover/ui/blob/0039b66606e19527749dbb7117f5fa9dfc426a9f/src/components/Document.js#L451

**Comment by gabriel-v** [comment]
Yeah, I think the text should look good after the `digests.gather` step [I linked above](https://github.com/hoover/snoop2/blob/dbdd60aced79ec50f0ecce93a4619d50d5b54211/snoop/data/digests.py#L74).  After this is fixed we can probably remove the UI `.trim()` call you linked above.

**Comment by grenwi** [comment]
It's definitely not about whitespace at the beginning/end of an extracted string. After some extracted data, empty cells in spreadsheets may result in hundreds of thousands of blank lines, then (maybe from a subsequent column or form another sheet) again some extracted data follows.

**Comment by gabriel-v** [comment]
It's even worse for HTML files; bleach with `strip = True` replaces HTML tags with spaces instead of removing them altogether, thus making the extracted text impossible to read.

**Comment by mgax** [comment]
By the way, we should treat lines that only contain whitespace as blank lines. A crafty regex can match them.
