### ISSUE TITLE
Add view for the File model

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/hoover-snoop2#159]
We have views for Digests and Directories, but not Files.

The UI needs access to the File model to properly show the file tree structure, since the digests are de-duplicated and will contain bad parent links.

The File view should probably also return the digest for that file.

**Comment by mgax** [comment]
That sounds reasonable. It would make sense to expose this structure with graphql.

**Comment by gabriel-v** [comment]
I wasn't suggesting we add graphql with this, just a new endpoint at https://github.com/hoover/snoop2/blob/dbdd60aced79ec50f0ecce93a4619d50d5b54211/snoop/data/views.py#L43 that gets the data for a File. This endpoint would be used in the UI file tree view.
