### ISSUE TITLE
Extract unnamed calendar attachment from emails

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/hoover-snoop2#74]
Some emails contain calendar (vcal?) attachments that have no filename, only these headers:

```
Content-Type: text/calendar; charset="utf-8"; method=CANCEL
Content-Transfer-Encoding: base64
```

It would be nice to show them as plain-text attachments.

When somebody decides to work on this, they should ping thiss issue and I'll add an example file to [testdata](https://github.com/liquidinvestigations/testdata) and link it here.

**Comment by gabriel-v** [comment]
moved https://github.com/CRJI/EIC/issues/568
